# Generated by Django 5.1.4 on 2025-03-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('read_date', models.DateField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='website.record')),
            ],
        ),
    ]
