# Generated by Django 5.1.4 on 2025-03-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='read_date',
            new_name='date_borrowed',
        ),
        migrations.AddField(
            model_name='book',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
